### ISSUE TITLE
Create Issues

### ISSUE THREAD

**Issue by schowbey** [schowbey/sp24-cse110-lab3#2]
#### Tasks
- [x] make issues template
- [x] make custom labels
- [x] create issues for each item in Lab 3
- [ ] use incremental pull-requests to resolve each issue
