### ISSUE TITLE
Add CSS

### ISSUE THREAD

**Issue by schowbey** [schowbey/sp24-cse110-lab3#3]
## Due Date: April 23
*Issue Description*: Add CSS to existing Lab 2 meetings notes
#### Tasks
- [x] create CSS file
- [x] link file to HTML file
- [x] add comments
- [x] change background color
- [x] use both absolute and relative sizing elements
- [x] style text using: color, text-decoration, and text-align
- [x] set sizing: height, width, max-width, min-width
- [x] positioning using 2 of: static, relative, fixed, absolute, sticky
- [x] use varying fonts from fonts.google
- [x] display properties using 2 of: none, block, inline-block, inline
- [x] make a CSS variable with fallback (provide a default value for a CSS variable in case the variable is not defined or supported by the browser)
