### ISSUE TITLE
CSS Box Models

### ISSUE THREAD

**Issue by schowbey** [schowbey/sp24-cse110-lab3#4]
## Due Date: April 23
*Issue Description*: use both long and short hand notations for each of the following: margin, padding, border
#### Tasks
- [x] long hand margins (margin-top, margin-bottom, margin-left, margin-right)
- [x] short hand margins (margin: <top> <right> <bottom> <left>)
- [x] auto margins (margin: auto)
- [x] long hand padding (padding-top, padding-bottom, padding-left, padding-right)
- [x] short hand padding (padding: <top> <right> <bottom> <left>)
- [x] border-style, border-color, border-width, border-radius
