### ISSUE TITLE
CSS Layouts and Responsiveness

### ISSUE THREAD

**Issue by schowbey** [schowbey/sp24-cse110-lab3#5]
## Due Date: 
*Issue Description*: 
#### Tasks
- [x] apply flex to the display property using flexbox (>2 two children within the flexbox element, >3 flexbox related attributes)
- [x] apply grid to the display property (>2 children within grid element, >3 grid related attributes)
- [x] 1+ query based on the screen width (viewport responsiveness)
