### ISSUE TITLE
CSS Selectors

### ISSUE THREAD

**Issue by schowbey** [schowbey/sp24-cse110-lab3#6]
## Due Date: April 23
*Issue Description*: use all of these CSS selectors
#### Tasks
- [x] class selector (.class)
- [x] ID selector (#id)
- [x] universal selector (*)
- [x] element selector (element) 
- [x] attribute selector (e.g. [attribute=foo])     
- [x] pseudo-class selector (e.g. p:hover)
- [x] selector list (element, element), select multiple elements
- [x] descendant combinator (element element)
- [x] child combinator (element > element)
- [x] general sibling combinator (element ~ element)
- [x] adjacent sibling combinator (element + element)
- [x] combining two selectors (element.class)
- [x] new Selectors :has()
- [x] nested selectors
